stages:
  - testBuild

# TODO: Variables for Mongo_URL

testBuild:
  image: docker:latest
  stage: testBuild
  services:
    # - docker:dind
    - mongo
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - docker info
  script:
    - docker build -t ms-registry:test .
  only:
    - master
  except:
    - tags  