stages:
  - test
  - build
  - push
  - deploy
image: 'docker:latest'
services:
  - 'docker:dind'
variables:
  PROJECT_NAME: ms-registry
  REL_IMAGE_TAG: '$CI_REGISTRY/$CI_PROJECT_PATH:latest'
  TEST_IMAGE_TAG: '$CI_REGISTRY/$CI_PROJECT_PATH:test'
test:
  stage: test
  variables:
    TEST_CMD: 'npm run test:docker'
  before_script:
    - docker pull mongo
    - docker network create --driver bridge mongo
    - docker run -d --name mongo --network mongo --expose 27017 --rm mongo
  script:
    - docker build --target test -t $TEST_IMAGE_TAG .
    - docker run --rm -d --network mongo --name $PROJECT_NAME $TEST_IMAGE_TAG
    - docker exec $PROJECT_NAME $TEST_CMD
  only:
    - master
  except:
    - tags
build:
  stage: build
  script:
    - docker build -t $REL_IMAGE_TAG .
    - docker save -o ms-registry.tar $REL_IMAGE_TAG
  artifacts:
    expire_in: 1h
    untracked: true
  only:
    - master
  except:
    - tags
push:
  stage: push
  before_script:
    - docker load < ms-registry.tar
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $REL_IMAGE_TAG
  dependencies:
    - build
  only:
    - master
  except:
    - tags
deploy:
  stage: deploy
  script:
    - >-
      docker run --rm aksakalli/mqtt-client pub -h test.mosquitto.org -t
      '/docker-deploy-mqtt/$DEPLOY_TOKEN' -m '{"imageName":
      "$CI_PROJECT_PATH", "imageTag": "latest"}'
  only:
    - master
  except:
    - tags
