stages:
  - testBuild

services:
  - mongo
  - docker:stable

# TODO: Variables for Mongo_URL

testBuild:
  stage: testBuild
  script:
    - docker build -t ms-registry:test --build-arg ENV=docker_test .
  only:
    - master
  except:
    - tags  