stages:
  - build
  - test
  - push
  - deploy

image: 'docker:latest'

services:
  - 'docker:dind'
  
variables:
  PROJECT_NAME: ms-registry
  IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH:latest
  TOPIC_SECRET: 23r90pahc3f9okj2ew09

build:
  stage: build
  script:
    - 'docker build -t $IMAGE_TAG .'
    - mkdir /docker-images
    - docker save -o ms-registry.tar $IMAGE_TAG
  artifacts:
    expire_in: 1h
    untracked: true
  only:
    - master
  except:
    - tags


test:
  stage: test
  variables:
    TEST_CMD: 'npm run test:docker'
  before_script:
    - docker pull mongo
    - docker network create --driver bridge mongo
    - docker run -d --name mongo --net mongo --expose 27017 --rm mongo
    - docker load < ms-registry.tar
  script:
    - docker run --entrypoint "" --net mongo --rm $IMAGE_TAG $TEST_CMD
  dependencies:
    - build
  only:
    - master
  except:
    - tags

push:
  stage: push

  before_script:
    - docker load < ms-registry.tar
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_TAG
  dependencies:
    - build
  only:
    - master
  except:
    - tags


deploy:
  stage: deploy
  script:
    - "docker run --rm aksakalli/mqtt-client pub -h test.mosquitto.org -t '/324rqndflasdyUHIcoqiwuebrlxiphuiqwerA89T' -m '{\"imageName\": \"$CI_PROJECT_PATH\", \"imageTag\": \"latest\"}'"
  only:
    - master
  except:
    - tags