stages:
  - testBuild

# TODO: Variables for Mongo_URL

testBuild:
  image: docker:latest
  stage: testBuild
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - docker info
    - docker network create --driver bridge mongo
    - docker pull mongo
    - docker run --rm -d --hostname mongo --name mongo --net mongo --expose 27017 mongo
  script:
    - docker build -t ms-registry:test .
    - docker run -d --net mongo --rm --name ms-registry ms-registry:test
    - docker network inspect mongo
    - docker exec ms-registry npm run test:docker
  only:
    - master
  except:
    - tags  