stages:
  - build
  - test
  - push

image: 'docker:latest'

services:
  - 'docker:dind'
  
variables:
  PROJECT_NAME: ms-registry
  IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME

build:
  stage: build
  script:
    - 'docker build -t $IMAGE_TAG .'
    - mkdir /docker-images
    - docker save -o ms-registry.tar $IMAGE_TAG
  artifacts:
    expire_in: 1h
    untracked: true
  only:
    - master
  except:
    - tags


test:
  stage: test
  variables:
    TEST_CMD: 'npm run test:docker'
  before_script:
    - docker pull mongo
    - docker network create --driver bridge mongo
    - docker run -d --name mongo --net mongo --expose 27017 --rm mongo
    - docker load < ms-registry.tar
  script:
    - 'docker run -d --net mongo --rm --name $PROJECT_NAME $IMAGE_TAG'
    - 'docker exec $PROJECT_NAME $TEST_CMD'
  dependencies:
    - build
  only:
    - master
  except:
    - tags

push:
  stage: push

  before_script:
    - docker load < ms-registry.tar
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_TAG
  dependencies:
    - build
  only:
    - master
  except:
    - tags
