stages:
  - testBuild

# TODO: Variables for Mongo_URL

testBuild:
  image: docker:stable
  services:
    - docker:dind
    - mongo
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  stage: testBuild
  script:
    - docker build -t ms-registry:test --build-arg ENV=docker_test .
  only:
    - master
  except:
    - tags  