language: node_js

node_js: 
  - 7
  - 8
  - 9
  - 10

branches:
  only:
    - master

install:
  - npm install

services:
  - mongodb
  - docker

script:
  - npm build
  - npm test

notifications:
  email:
    on_success: never
    on_failure: always